// ui
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const LOG_DONATED = "LOG_DONATED";

// search
export const RESET_SEARCH = "RESET_SEARCH";
export const HIDE_SEARCH_PLACEHOLDER = "HIDE_SEARCH_PLACEHOLDER";
export const SHOW_SEARCH_PLACEHOLDER = "SHOW_SEARCH_PLACEHOLDER";
export const UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY";
export const SHOW_SEARCH_SPINNER = "SHOW_SEARCH_SPINNER";
export const DOWNLOAD_COMPLETE = "DOWNLOAD_COMPLETE";
export const SEARCH_BY_QUERY = "SEARCH_BY_QUERY";
export const SEARCH_BY_FILES = "SEARCH_BY_FILES";
export const DROP_FILES = "DROP_FILES";
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";
export const INCREASE_SEARCH_ATTEMPTS = "INCREASE_SEARCH_ATTEMPTS";
export const LOG_SEARCH_QUERY = "LOG_SEARCH_QUERY";
